### ISSUE TITLE
Error: Cannot find module 'attiny-common'

### ISSUE THREAD

**Issue by mediafreakch** [tessel/ambient-attx4#53]
I installed `ambient-attx4` and tried to run the [example](http://tessel.github.io/t2-start/modules/ambient.html#step-4) given on tessel.io. However I get the following error when doing `t2 run src/ambient.js`:

```
INFO Running src/ambient.js...
module.js:339
    throw err;
    ^

Error: Cannot find module 'attiny-common'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/remote-script/node_modules/ambient-attx4/index.js:1:897)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Seems that after deploying, the ambient-attx4 module cannot resolve attiny-common anymore...
I verified that attiny-common is installed in my node_modules folder (0.0.9)

**Comment by johnnyman727** [comment]
As a helpful debugging step, could you re-run this command as `t2 run src/ambient.js --full`? We have some preprocessing steps that minifies the bundle to send over and I want to see if that's the source of the problem.

**Comment by mediafreakch** [comment]
@johnnyman727 Unfortunately there seems to be not enough space on the RAM to host the full source:

```
INFO Building project.
WARN Pre-compiled module is missing: usb.
This might be caused by any of the following:

1. The binary is platform specific and cannot be compiled for OpenWRT.
2. A pre-compiled binary has not yet been generated for this module.
3. The binary didn't compile correctly for the platform that you're developing on.
    It's possible that the binary is Linux-only or even OpenWRT specific,
    try npm installing with "--force" and rerun your deployment command.

Please file an issue at https://github.com/tessel/t2-cli/issues/new
INFO Writing project to RAM on Tessel-xyz (39468.544 kB)...
ERR! Error: tar: write error: No space left on device
```

Is there another way I can provide you the required debugging information?

**Comment by rwaldron** [comment]
Can you paste the output of running `tree` in your project root

**Comment by mediafreakch** [comment]
@rwaldron I'm on Mac OSX, but the file attached should give you the information you requested. 
[tree.txt](https://github.com/tessel/ambient-attx4/files/211868/tree.txt)

**Comment by rwaldron** [comment]
> @rwaldron I'm on Mac OSX, but ...

I don't understand the "but"? I'm on OSX and use tree. It's going to take me some time to sort through this file, I doubt I'll get to it until tomorrow

**Comment by mediafreakch** [comment]
@rwaldron It's not installed by default and I had some issues installing it. Now here it is: https://gist.github.com/mediafreakch/5a31ad3b975094db59349f4309f552a0

**Comment by johnnyman727** [comment]
@mediafreakch based on the output of that log, it looks like you're trying to deploy thousands of files from many different projects.

I recommend following the directions [on the Start experience](http://tessel.github.io/t2-start/modules/ambient.html) closely to ensure you deploy only the proper project.

**Comment by mediafreakch** [comment]
@johnnyman727 I did not have installed `t2-cli` globally but locally instead. Couldn't test the difference yet, but why should that be an issue?

**Comment by johnnyman727** [comment]
@mediafreakch you have to be careful to have a `package.json` in the proper place because when you do `t2 run ...` the CLI needs to find the top level of the project (root) to bundle up. If you don't have a package.json, it could continue traversing up your file system until it finds one. If it goes beyond your project directory, then it could easily bundle up a folder that has many other folders (which aren't used in your project) and it will exceed the memory limit.

**Comment by mediafreakch** [comment]
@johnnyman727 what is the role of a `package.json` when running `t2 run ...` ? Bundling should resolve by the files that I `require`, not the packages listed in `dependencies` or `devDependencies`?! My directory structure was fairly simple:

```
./tessel
  node_modules/ --> ambient-attx4 + t2-cli deps
  src/
  node_modules/  --> my way to organize my source code
    ambient/
      index.js
      package.json
  ambient.js --> "require('ambient')"
  package.json
```

My package.jsons:

```
// ./package.json
{
  "name": "tessel",
  "main": "src/ambient.js",
  "devDependencies": {
    "ambient-attx4": "^0.2.8",
    "t2-cli": "0.0.16"
  }
}
```

```
// ./src/node_modules/ambient/package.json
{
  "name": "ambient"
}
```

I will try to redo exactly as in the example when I'm back home. Nevertheless I see nothing unusual on my side...

**Comment by rwaldron** [comment]
> Bundling should resolve by the files that I require

That's exactly what it does. In order to for the `t2 [run|push]` mechanism to be friendly to developers of modules, applications and tooling (not always a human deploying the code), there is a minimal requirement that a Tessel 2 _project_ must contain a package.json in its root directory. That package.json is then used by the tool to determine where to stop traversing the filesystem when determining where to start bundling. 

Let's say I'm writing a new Tessel 2 module and I have a directory structure like this: 

```
rwaldron at nova in ~/robotz/tessel-module
$ tree
.
├── examples
│   └── leds-1-on.js
├── lib
│   └── index.js
└── package.json

2 directories, 3 files
```

If I were to execute: `cd ~/ && t2 run robotz/tessel-module/examples/leds-1-on.js`, the tool will accept that entry point and start looking for the project root. Once it finds the package.json (one level up), it can safely assume that it's reached the project root—because that's the semantics that were specified and documented for that command. If there was no such rule, how would the tool ever know where to stop looking and start bundling? 

Here's what running that command looks like: 

```
$ t2 run robotz/tessel-module/examples/leds-1-on.js
INFO Looking for your Tessel...
INFO Connected to bishop.
INFO Building project.
INFO Writing project to RAM on bishop (4.096 kB)...
INFO Deployed.
INFO Running examples/leds-1-on.js...
```

Notice that `t2 run` found the appropriate root of the project and then ran the entry point file accordingly? Without that package.json, there is no concrete way to determine where the project root is. Since package.json files have become ubiquitous, it's really not a burden to just require that one exists. To make that even easier, the tool has a super simple command to make one for you. 


> not the packages listed in dependencies or devDependencies?!

Hopefully my explanation has made it clear that this is not the case.

**Comment by rwaldron** [comment]
I'm reopening this until I have a better resolution for the original report

**Comment by rwaldron** [comment]
I will this issue from the t2-cli patch

**Comment by mediafreakch** [comment]
> Hopefully my explanation has made it clear that this is not the case.

I understand the use case you described and it makes sense to me. However it doesn't work:

`t2 run src/ambient.js`

```
esch$ tree
.
├── node_modules
│   ├── ambient-attx4
│   ├── async
│   ├── attiny-common
│   ├── avr-isp
│   └── sync-queue
├── package.json
└── src
    └── ambient.js
```

This works:

`t2 run ambient.js`

```
esch$ tree
.
├── ambient.js
├── node_modules
│   ├── ambient-attx4
│   ├── async
│   ├── attiny-common
│   ├── avr-isp
│   └── sync-queue
└── package.json
```

I haven't tested your patch. Did you intend to fix that issue with it?

**Comment by rwaldron** [comment]
> I haven't tested your patch. Did you intend to fix that issue with it? 

Yessir :)

**Comment by rwaldron** [comment]
@mediafreakch I've just landed the fix (reviewed by @HipsterBrown) in t2-cli. We will leave this open until a new version of t2-cli is released and you can confirm that fix yourself. Sound good?

**Comment by mediafreakch** [comment]
Perfectly fine! Many thanks. I can start hacking now :)
